version : "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    restart: always
    depends_on: 
      - wordpress
    ports:
      - "443:443"
    networks: 
      - inception_network
    volumes:
      - wp_volume:/var/www/
    # tty: true

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file: .env
    networks: 
      - inception_network
    volumes:
      - db_volume:/var/lib/mysql/
    # tty: true

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on: 
      - mariadb
    restart: always
    env_file: .env
    networks: 
      - inception_network
    volumes:
      - wp_volume:/var/www/  
    # tty: true

networks:
  inception_network:
    driver: bridge

volumes:
  db_volume:
    driver_opts:
      type: volume
      o : 'bind'
      device: '/home/sesim/data/mariadb'

  wp_volume:
    driver_opts:
      type: volume
      o : 'bind'
      device: '/home/sesim/data/wordpress'
